// TODO: Include packages needed for this application
const inquirer = require('inquirer');
const fs = require('fs');

// TODO: Create an array of questions for user input
const questions = [

  //-----------------------------## Project Title
  {
    type: 'input',
    message: 'What is the name of your project?',
    name: 'title',
  },
  //-----------------------------## Description
  {
    type: 'input',
    message: 'Please provide a description of your project.',
    name: 'description',
  },
  //-----------------------------## Installation
  {
    type: 'input',
    message: 'Please provide a description for the steps required to install your project.',
    name: 'install',
  },
  //-----------------------------## Usage
  {
    type: 'input',
    message: 'Please provide a description on usages.',
    name: 'usage',
  },
  /*{
    type: 'input',
    message: 'Where can your live site be found?',
    name: 'liveSite',
  },*/
  //-----------------------------## Credits
  {
    type: 'input',
    message: 'Please list any collaborators or site any outside sources.',
    name: 'credit',
  },
  //-----------------------------## License
  {
    type: 'list',
    message: 'Please choose a list.',
    name: 'license',
    choices: ['MIT', 'Boost Software License - Version 1.0', 'The Unlicense',],
  },
  //-----------------------------## Questions
  {
    type: 'input',
    message: 'What is your gitHub user name?',
    name: 'gitHubName',
  },
  {
    type: 'input',
    message: 'What is your email address?',
    name: 'email',
  },
];

//----------------------------- 
inquirer.prompt(questions).then((answers) => {
  const readMeContent = generateReadMe(answers);
  //const badge = createBadge(answers);
  //const text = createText(answers);

  //----------------------------- Write file to README.md
  fs.writeFile('README.md', readMeContent, (err) =>
    err ? console.log(err) : console.log('Successfully created README.md!')
  );
});


/*
//----------------------------- Create License Badge
const createBadge = (license) => {
  switch(license){
    case 'MIT':
      licenseBadge = '';
      return licenseBadge;
      break;
    case 'Boost Software License - Version 1.0':
      licenseBadge = '';
      return licenseBadge;
      break;
    case 'The Unlicense':
      licenseBadge = '';
      return licenseBadge;
      break;
    Default:
    licenseBadge = '';
      return licenseBadge;
      console.log(licenseBadge);
  }
  };



  
//----------------------------- Create License Text
const createText = (license) => {
  switch(license){
    case 'MIT':
      licenseText = `Copyright (c) 2022 swmcguire 
      
      Permission is hereby granted, free of charge, to any person obtaining a copy
      of this software and associated documentation files (the "Software"), to deal
      in the Software without restriction, including without limitation the rights
      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
      copies of the Software, and to permit persons to whom the Software is
      furnished to do so, subject to the following conditions:
      
      The above copyright notice and this permission notice shall be included in all
      copies or substantial portions of the Software.
      
      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
      FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
      AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
      LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
      OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
      SOFTWARE.`;
      return licenseText;
      break;
    case 'Boost Software License - Version 1.0':
      licenseText = `Boost Software License - Version 1.0 - January 1, 2023

      Permission is hereby granted, free of charge, to any person or organization
      obtaining a copy of the software and accompanying documentation covered by
      this license (the "Software") to use, reproduce, display, distribute,
      execute, and transmit the Software, and to prepare derivative works of the
      Software, and to permit third-parties to whom the Software is furnished to
      do so, all subject to the following:
      
      The copyright notices in the Software and this entire statement, including
      the above license grant, this restriction and the following disclaimer,
      must be included in all copies of the Software, in whole or in part, and
      all derivative works of the Software, unless such copies or derivative
      works are solely in the form of machine-executable object code generated by
      a source language processor.
      
      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
      IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
      FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
      SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
      FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
      ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
      DEALINGS IN THE SOFTWARE.`;
      return licenseText;
      break;
    case 'The Unlicense':
      licenseText = `This is free and unencumbered software released into the public domain.

      Anyone is free to copy, modify, publish, use, compile, sell, or
      distribute this software, either in source code form or as a compiled
      binary, for any purpose, commercial or non-commercial, and by any
      means.
      
      In jurisdictions that recognize copyright laws, the author or authors
      of this software dedicate any and all copyright interest in the
      software to the public domain. We make this dedication for the benefit
      of the public at large and to the detriment of our heirs and
      successors. We intend this dedication to be an overt act of
      relinquishment in perpetuity of all present and future rights to this
      software under copyright law.
      
      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
      EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
      MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
      IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
      OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
      ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
      OTHER DEALINGS IN THE SOFTWARE.
      
      For more information, please refer to <https://unlicense.org>`;
      return licenseText;
      break;
    Default:
      licenseText = '';
      return licenseText;
console.log(licenseText);
  }
  };
*/

const generateReadMe = ({ title, description, install, usage, credit, license, licenseText, email, gitHubName}) =>
`# ${title}

## Description
${description}

## Table of Contents
- [Installation](#installation)
- [Usage](#usage)
- [Credits](#credits)
- [License](#license)
- [Contributing](#contributing)
- [Tests](#tests)
- [Questions](#questions)

## Installation Instructions
${install}

## Usage
${usage}

## Credits
${credit}

## License
${license} License
This project is using the ${license} License.

## Contributing
If you'd like to contribute please feel free to reach out at ${email}

## Tests
Not Applicable in this project.

## Questions
If you have any questions or would like to see any of my other repositories feel free to connect via https://github.com/${gitHubName}
Any additional questions please reach out to me directly at ${email}`
